# Generated by Django 4.2.4 on 2023-08-12 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_day', models.DateTimeField(default=django.utils.timezone.now, verbose_name='День оплаты')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма оплаты')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('account_transfer', 'Банковский перевод')], max_length=17, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_hub.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_hub.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-payment_day',),
            },
        ),
    ]
