# Generated by Django 4.2.4 on 2023-08-17 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_hub', '0002_course_course_owner_lesson_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец урока'),
            preserve_default=False,
        ),
    ]
