# Generated by Django 4.2.4 on 2023-08-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub', '0003_alter_course_course_owner_alter_lesson_lesson_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'title'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
